export enum ExportWizardStep {
    TARGET_PICKER = 'TARGET_PICKER',
    SQL_TARGET = 'SQL_TARGET',
    SQL_PREVIEW = 'SQL_PREVIEW',
    DBML_PREVIEW = 'DBML_PREVIEW',
    JSON_DOWNLOAD = 'JSON_DOWNLOAD',
    VISUAL_OPTIONS = 'VISUAL_OPTIONS',
    LARAVEL_OPTIONS = 'LARAVEL_OPTIONS',
    PRISMA_VERSION = 'PRISMA_VERSION',
    PRISMA_PREVIEW = 'PRISMA_PREVIEW',
    EF_CORE_OPTIONS = 'EF_CORE_OPTIONS',
    EF_CORE_RESULT = 'EF_CORE_RESULT',
    RAILS_RESULT = 'RAILS_RESULT',
}
