import type { PrismaVersionProfile } from './prisma-version-profile';
import type { PrismaDatasourceProvider } from './prisma-export-capability';
import type { PrismaExportNote } from './prisma-export-types';
import { escapePrismaComment } from './prisma-escape';

export interface PrismaEnumBlock {
    identifier: string;
    physicalName: string;
    values: Array<{
        prismaName: string;
        physicalValue: string;
        needsMap: boolean;
    }>;
}

export interface PrismaScalarFieldLine {
    prismaName: string;
    physicalName: string;
    typeExpression: string;
    attributes: string[];
    documentation?: string;
}

export interface PrismaRelationFieldLine {
    prismaName: string;
    typeExpression: string;
    attributes: string[];
}

export interface PrismaModelBlock {
    identifier: string;
    physicalName: string;
    needsTableMap: boolean;
    scalarFields: PrismaScalarFieldLine[];
    relationFields: PrismaRelationFieldLine[];
    blockAttributes: string[];
    documentation?: string;
}

export interface PrismaSchemaDocument {
    enums: PrismaEnumBlock[];
    models: PrismaModelBlock[];
    notes: PrismaExportNote[];
}

const indent = (level: number): string => '  '.repeat(level);

export const writePrismaSchema = (
    document: PrismaSchemaDocument,
    profile: PrismaVersionProfile,
    provider: PrismaDatasourceProvider
): string => {
    const lines: string[] = [];

    lines.push('// Generated by FoxalDB');
    lines.push(
        '// Review limitation notes before using this schema in production.'
    );

    document.notes.forEach((note) => {
        lines.push(
            `// FoxalDB [${note.code}]: ${escapePrismaComment(note.message)}`
        );
    });

    lines.push('');
    lines.push('generator client {');

    if (profile.clientOutput) {
        lines.push(`  provider = "${profile.clientProvider}"`);
        lines.push(`  output   = "${profile.clientOutput}"`);
    } else {
        lines.push(`  provider = "${profile.clientProvider}"`);
    }

    lines.push('}');
    lines.push('');
    lines.push('datasource db {');
    lines.push(`  provider = "${provider}"`);

    if (profile.datasourceUrlInSchema) {
        lines.push('  url      = env("DATABASE_URL")');
    }

    lines.push('}');

    document.enums.forEach((enumBlock) => {
        lines.push('');
        writeEnumBlock(lines, enumBlock);
    });

    document.models.forEach((model) => {
        lines.push('');
        writeModelBlock(lines, model);
    });

    lines.push('');

    return lines.join('\n');
};

const writeEnumBlock = (lines: string[], enumBlock: PrismaEnumBlock): void => {
    lines.push(`enum ${enumBlock.identifier} {`);

    enumBlock.values.forEach((value) => {
        const mapAttribute = value.needsMap
            ? ` @map(${JSON.stringify(value.physicalValue)})`
            : '';

        lines.push(`  ${value.prismaName}${mapAttribute}`);
    });

    if (enumBlock.physicalName !== enumBlock.identifier) {
        lines.push('');
        lines.push(`  @@map(${JSON.stringify(enumBlock.physicalName)})`);
    }

    lines.push('}');
};

const writeModelBlock = (lines: string[], model: PrismaModelBlock): void => {
    if (model.documentation) {
        lines.push(`/// ${escapePrismaComment(model.documentation)}`);
    }

    lines.push(`model ${model.identifier} {`);

    model.scalarFields.forEach((field) => {
        if (field.documentation) {
            lines.push(
                `${indent(1)}/// ${escapePrismaComment(field.documentation)}`
            );
        }

        const attributeSuffix =
            field.attributes.length > 0 ? ` ${field.attributes.join(' ')}` : '';

        lines.push(
            `${indent(1)}${field.prismaName} ${field.typeExpression}${attributeSuffix}`
        );
    });

    model.relationFields.forEach((field) => {
        const attributeSuffix =
            field.attributes.length > 0 ? ` ${field.attributes.join(' ')}` : '';

        lines.push(
            `${indent(1)}${field.prismaName} ${field.typeExpression}${attributeSuffix}`
        );
    });

    model.blockAttributes.forEach((attribute) => {
        lines.push(`${indent(1)}${attribute}`);
    });

    if (model.needsTableMap) {
        lines.push(`${indent(1)}@@map(${JSON.stringify(model.physicalName)})`);
    }

    lines.push('}');
};

export const stripVersionSpecificHeader = (schema: string): string =>
    schema.replace(/^[\s\S]*?(?=^(enum|model)\s)/m, '');
