/**
 * Detect if SQL content is from Oracle format
 */
export function isOracleFormat(sqlContent: string): boolean {
    const oracleMarkers = [
        'VARCHAR2',
        'NUMBER(',
        'SYSDATE',
        'SYSTIMESTAMP',
        'SYS_GUID',
        'GENERATED ALWAYS AS IDENTITY',
        'GENERATED BY DEFAULT AS IDENTITY',
        '.NEXTVAL',
        'TABLESPACE',
        'PCTFREE',
        'STORAGE (',
        'NVARCHAR2',
        'CLOB',
        'NCLOB',
        'BLOB',
        'BFILE',
        'BINARY_FLOAT',
        'BINARY_DOUBLE',
        'ROWID',
        'XMLTYPE',
        'CREATE SEQUENCE',
        'CREATE OR REPLACE',
        'CONSTRAINT .* PRIMARY KEY.*ENABLE',
    ];

    // Check for specific Oracle patterns
    for (const marker of oracleMarkers) {
        if (marker.includes('.*')) {
            // Handle regex patterns
            const regex = new RegExp(marker, 'i');
            if (regex.test(sqlContent)) {
                return true;
            }
        } else if (sqlContent.toUpperCase().includes(marker.toUpperCase())) {
            return true;
        }
    }

    return false;
}
